[package]
name = "toxo"
version = "0.1.0"
edition = "2021"

[dependencies]
blake3 = "1.5.4"
chrono = "0.4.38"
duckdb = { version = "1.1.1", features = ["bundled"] }
maxminddb = "0.24.0"
serde = "1.0.213"
serde_json = "1.0.132"
serde_yaml = "0.9.34"
ua-parser = "0.2.0"
url = "2.5.2"
