on:
  release:
    types:
      - created

jobs:
  linux_x86_64:
    runs-on: ubuntu-latest
    steps:
      - name: Install rustup targets
        run: rustup target add x86_64-unknown-linux-gnu

      - name: Build the executable
        run: cargo build --release --target=x86_64-unknown-linux-gnu --locked -j4

      - name: Tar Binary
        run: tar -czvf log2duck-x86_64-unknown-linux-gnu.tar.gz -C target/x86_64-unknown-linux-gnu/release log2duck

      - name: Generate SHA256 checksum
        run: shasum -a 256 log2duck-x86_64-unknown-linux-gnu.tar.gz > log2duck-x86_64-unknown-linux-gnu.tar.gz.sha256

      - name: Upload release binaries
        uses: actions/upload-artifact@v4
        with:
          name: log2duck-x86_64-apple-darwin
          path: |
            log2duck-x86_64-unknown-linux-gnu.tar.gz
            log2duck-x86_64-unknown-linux-gnu.tar.gz.sha256

  mac_x86_64:
    runs-on: macos-latest
    steps:
      - name: Install rustup targets
        run: rustup target add x86_64-apple-darwin

      - name: Build the executables
        run: cargo build --release --target=x86_64-apple-darwin --locked -j4

      - name: Tar binary
        run: tar -czvf log2duck-x86_64-apple-darwin.tar.gz -C target/x86_64-apple-darwin/release log2duck

      - name: Generate SHA256 checksum
        run: shasum -a 256 log2duck-x86_64-apple-darwin.tar.gz > log2duck-x86_64-apple-darwin.tar.gz.sha256

      - name: Upload release binaries
        uses: actions/upload-artifact@v4
        with:
          name: log2duck-x86_64-apple-darwin
          path: |
            log2duck-x86_64-apple-darwin.tar.gz
            log2duck-x86_64-apple-darwin.tar.gz.sha256

  mac_aarch64:
    runs-on: macos-latest
    steps:
      - name: Install rustup targets
        run: rustup target add aarch64-apple-darwin

      - name: Build the executables
        run: cargo build --release --target=aarch64-apple-darwin --locked -j4

      - name: Tar binaries
        run: tar -czvf log2duck-aarch64-apple-darwin.tar.gz -C target/aarch64-apple-darwin/release log2duck

      - name: Generate SHA256 checksums
        run: shasum -a 256 log2duck-aarch64-apple-darwin.tar.gz > log2duck-aarch64-apple-darwin.tar.gz.sha256

      - name: Upload release binaries
        uses: actions/upload-artifact@v4
        with:
          name: log2duck-x86_64-apple-darwin
          path: |
            log2duck-aarch64-apple-darwin.tar.gz
            log2duck-aarch64-apple-darwin.tar.gz.sha256
